version: "3"
services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - ./volumes/usr/share/nginx/html/swagger:/usr/share/nginx/html/swagger
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: swagger-editor
    environment:
      - BASE_URL=/editor
    restart: always
    ports:
      - "8083:8080"
