version: "3"
services:
  jenkins-dind:
    image: docker:dind
    container_name: jenkins-dind
    privileged: true
    restart: always
    environment:
      - DOCKER_TLS_CERTDIR=
    #volumes:
     # - ./volumes/etc/resolv.conf:/etc/resolv.conf
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8082:8080"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - DOCKER_HOST=tcp://gitlab-runner-dind:2375/
      - DOCKER_DRIVER=overlay2
    volumes:
      - ./volumes/var/jenkins_home:/var/jenkins_home
