version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
      - "13060:33060"
    volumes:
      - ./volumes/var/lib/mysql:/var/lib/mysql
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Hong_Kong"
