version: "3"
services:
  posgres:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/var/lib/postgresql
    network_mode: bridge
    environment:
      POSTGRES_PASSWORD: "password"
      TZ: "Asia/Hong_Kong"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
